version: '3.9'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB_DATABASE: challenge
    command: --auth

    ports:
      - 27017:27017
  
  web:
    build: 
      context: .
      dockerfile: DockerFile
    container_name: chucknorris
    command: npm run start
    restart: unless-stopped

    volumes:
      - .:/usr/src/app/
    ports:
      - "4000:4000"  
    links:
      - mongodb 
    depends_on: 
      - mongodb
    
